// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG10JC6AbZboBc4QU8Xbv0z1MOCfqZDPE',
    appId: '1:112255882372:web:5686ba521346b10773ded1',
    messagingSenderId: '112255882372',
    projectId: 'sinfuldelights-91726',
    authDomain: 'sinfuldelights-91726.firebaseapp.com',
    storageBucket: 'sinfuldelights-91726.firebasestorage.app',
    measurementId: 'G-LJFRKHK51W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWq-oYq2kjDRHsk0_9pW055MQhzM2Tu0c',
    appId: '1:112255882372:android:e06be9a66c8b3a6173ded1',
    messagingSenderId: '112255882372',
    projectId: 'sinfuldelights-91726',
    storageBucket: 'sinfuldelights-91726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZ3q5lsJyOwS5UpjlCZsRupoUG6NOCwE',
    appId: '1:112255882372:ios:6676dcad4e18bd9f73ded1',
    messagingSenderId: '112255882372',
    projectId: 'sinfuldelights-91726',
    storageBucket: 'sinfuldelights-91726.firebasestorage.app',
    iosClientId: '112255882372-kuot6cjsk9h0h85223gfr2qbomrqvhrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sinfuldelightsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZ3q5lsJyOwS5UpjlCZsRupoUG6NOCwE',
    appId: '1:112255882372:ios:6676dcad4e18bd9f73ded1',
    messagingSenderId: '112255882372',
    projectId: 'sinfuldelights-91726',
    storageBucket: 'sinfuldelights-91726.firebasestorage.app',
    iosClientId: '112255882372-kuot6cjsk9h0h85223gfr2qbomrqvhrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sinfuldelightsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG10JC6AbZboBc4QU8Xbv0z1MOCfqZDPE',
    appId: '1:112255882372:web:974b215a67fe3f8373ded1',
    messagingSenderId: '112255882372',
    projectId: 'sinfuldelights-91726',
    authDomain: 'sinfuldelights-91726.firebaseapp.com',
    storageBucket: 'sinfuldelights-91726.firebasestorage.app',
    measurementId: 'G-Y6ZT54YXM6',
  );
}
